"""empty message

Revision ID: ce1f18c4395b
Revises: 4c430a52b40f
Create Date: 2022-08-30 09:40:48.145016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1f18c4395b'
down_revision = '4c430a52b40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'email')
    # ### end Alembic commands ###
